browser:
  browser_type: chromium
  headless: true
  linkedin_manual_login: false
  timeout: 30000
  user_data_dir: null
  window_size:
    height: 1080
    width: 1920
crawl:
  max_retries: 3
  rate_limit: 1.0
  timeout: 30
  user_agent: Mozilla/5.0 Job Application Automation Bot
data_dir: ../data
linkedin:
  client_id: '***'
  client_secret: '***'
  redirect_uri: http://localhost:8000/callback
  session_path: ../data/sessions
  use_api: true
  use_mcp: true
llm:
  api_key: '***'
  max_tokens: 4000
  model: gpt-4
  provider: openai
  temperature: 0.7
logging:
  backup_count: 5
  console_logging: true
  file_logging: true
  file_path: ../data/logs/application.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  log_dir: ../data/logs
  log_format: standard
  max_file_size: 10485760
  max_size_mb: 10
max_applications_per_run: 5
min_match_score: 0.7
security:
  encrypt_sensitive_data: true
  encryption_key_path: null
  secure_delete: true
  use_keyring: true
