browser:
  browser_type: chromium
  headless: true
  linkedin_manual_login: false
  timeout: 30000
  user_data_dir: null
  window_size:
    height: 1080
    width: 1920

job_sources:
  linkedin:
    enabled: true
    client_id: '***'
    client_secret: '***'
    redirect_uri: http://localhost:8000/callback
    session_path: ../data/sessions
    use_api: true
    use_mcp: true
    rate_limit: 60  # requests per minute
  indeed:
    enabled: true
    api_key: '***'
    publisher_id: '***'
    rate_limit: 60
  glassdoor:
    enabled: true
    partner_id: '***'
    api_key: '***'
    rate_limit: 60

llm:
  provider: github  # github, groq, openrouter, local
  api_key: '***'
  model: meta/Llama-4-Maverick-17B-128E-Instruct-FP8
  max_tokens: 4000
  temperature: 0.7
  local_model:
    model_path: ../models/llama-3-8b.gguf
    use_gpu: true
    gpu_layers: 32

document_generation:
  templates_dir: ../templates
  styles:
    - modern
    - classic
    - creative
  resume:
    formats:
      - docx
      - pdf
    sections:
      - summary
      - experience
      - education
      - skills
      - projects
  cover_letter:
    formats:
      - docx
      - pdf
    styles:
      - formal
      - casual
      - creative

job_matching:
  min_match_score: 0.7
  weights:
    skills: 0.4
    experience: 0.3
    education: 0.2
    keywords: 0.1
  vector_search:
    enabled: true
    index_type: HNSW  # HNSW, Flat, IVF
    dimension: 768
    metric: cosine

application_tracking:
  max_applications_per_run: 5
  auto_follow_up: true
  follow_up_intervals:
    - 7  # days after application
    - 14
    - 30
  status_notifications: true
  email_notifications: true

resume_optimization:
  strategies:
    keyword_optimization: true
    skill_matching: true
    experience_highlighting: true
  ab_testing: true
  min_improvement: 0.1  # 10% improvement threshold

data_dir: ../data
logging:
  backup_count: 5
  console_logging: true
  file_logging: true
  file_path: ../data/logs/application.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  log_dir: ../data/logs
  log_format: standard
  max_file_size: 10485760
  max_size_mb: 10

security:
  encrypt_sensitive_data: true
  encryption_key_path: null
  secure_delete: true
  use_keyring: true
  api_key_storage: keyring  # keyring, file, environment
